services:
  db:
    image: postgres:16-alpine
    container_name: auth-psql
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - my-network


  app:
    image: auth_service
    container_name: auth-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - my-network


networks:
  my-network:
    name: my-network