server:
  port: "8080"

logger:
  level: "debug"
  file_name: "./server.log"

# database:
#   host: "localhost"
#   port: 5432
#   user: "auth_user"
#   password: "auth_password"
#   dbname: "auth_db"